language: python

sudo: false

python:
  - "2.7"

install:
#   - pip install --upgrade pip setuptools wheel
#   - pip install --only-binary=numpy,scipy numpy scipy
  
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE="http://repo.continuum.io/miniconda/Miniconda"
  - if [[ "${TRAVIS_PYTHON_VERSION}" == 2* ]]; then
      wget ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the testing environment
  # ------------------------------
  - conda config --set always_yes true
  - conda config --set changeps1 no
  - conda config --set show_channel_urls true
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME="test-environment"
  - conda create --quiet -n ${ENV_NAME} python=${TRAVIS_PYTHON_VERSION}
  - source activate ${ENV_NAME}
  # Customise the testing environment
  # ---------------------------------
  - python setup.py install

script:
  - python setup.py test